name = "registry-edge"
workers_dev = true
compatibility_date = "2022-08-25"
compatibility_flags = [
  "url_standard"
]

main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.16"

[build]
command = "worker-build --release"
